#!/usr/bin/sh

oslist="Ubuntu Debian CentOS"
for linux in $oslist; do
	os=`grep -o -a -m 1 -h -r "$linux" /etc/issue | head -1`
done
	
if [ "CentOS" == "$os" ]
then
	echo "Waiting ...."
	echo "Installing packages ...."
	yum install automake autoconf
	yum install libtool
	yum install libtool-ltdl-devel
	yum install uuid-devel
	yum install uuid
	yum install libxml++-devel
	yum install sqlite-devel
	echo "Successfully installed packages"

elif [ "$os" == "Ubuntu" ] || [ "$os" == "Debian" ]
then
	echo "Waiting ...."
	echo "Installing packages ...."
	apt-get install automake autoconf
	apt-get install libtool
	apt-get install libltdl-dev
	apt-get install sqlite3 libsqlite3-dev
	apt-get install libxml++2.6-dev
	apt-get install uuid-dev
	echo "Successfully installed packages"

else
	echo "$os is NOT match"
fi
exit 0
